### ISSUE TITLE
First Element of JTree is not displayed

### ISSUE THREAD

**Issue by nhacken** [cbfiddle/Issues#3]
When having the VAqua look and feel active, the first element of my JTree GUI Items are not displayed. One of them sometimes do not display at all, while the first element is always missing (in both of my JTree Elements). Since I didn't want to dig my code, I don't know whether a reload of the Tree would solve the display issue, but the missing first element does not appear.

**Comment by cbfiddle** [comment]
Are you using the sidebar tree style?

**Comment by nhacken** [comment]
No, I did not apply the Sidebar tree style, but tried with and without the striped option.

**Comment by cbfiddle** [comment]
I have not seen a problem like this. I suggest making sure that the creation and updates to the tree are made on the AWT event thread.

**Comment by nhacken** [comment]
Ok, thanks. This will cost me a lot of work which is very low-prio since I found a workaround to the use of VAqua (at least for the moment). But I will keep it in mind and try to migrate my whole UI to the AWT Thread. This is not that easy, since there's some interaction between the main thread and the UI, so I'm not sure how quick i'll be.
I'll be back to you when i get a definitive answer (same for #4 )
Meanwhile, thanks a lot for the nice tool

**Comment by nhacken** [comment]
This one is harder... still even when executed inside the AWT Thread, the first element (root) of the JTree are not displayed (but still exist)

**Comment by cbfiddle** [comment]
The default in VAqua is to hide the root.
The solution:
`tree.setRootVisible(true);`

**Comment by nhacken** [comment]
That's it, it works great, Thanks!!
Now it is only running in a mockup-version of my application, will try to build it into the main application when I find some "spare" time.
